"""widen Track with remaining kmeans audio features T33

Revision ID: ce6e2ca7edac
Revises: fe4e66a13f08
Create Date: 2026-07-27 15:37:15.045974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ce6e2ca7edac'
down_revision: Union[str, None] = 'fe4e66a13f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Track', sa.Column('acousticness', sa.Float(), nullable=True), schema='silver')
    op.add_column('Track', sa.Column('instrumentalness', sa.Float(), nullable=True), schema='silver')
    op.add_column('Track', sa.Column('liveness', sa.Float(), nullable=True), schema='silver')
    op.add_column('Track', sa.Column('speechiness', sa.Float(), nullable=True), schema='silver')
    op.add_column('Track', sa.Column('mode', sa.Float(), nullable=True), schema='silver')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Track', 'mode', schema='silver')
    op.drop_column('Track', 'speechiness', schema='silver')
    op.drop_column('Track', 'liveness', schema='silver')
    op.drop_column('Track', 'instrumentalness', schema='silver')
    op.drop_column('Track', 'acousticness', schema='silver')
    # ### end Alembic commands ###
